---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mydb
spec:
  containers:
    - name: mydb
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: intelliqit
      volumeMounts:
        - name: my-volume
          mountPath: /var/lib/mysql
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
...

