---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    author: intelliqit
spec:
  containers:
    - name: mynginx
      image: nginx
      ports: 
       - containerPort: 80
         hostPort: 8888
...
