---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: any
  namespace: testnamespace
spec:
  containers:
    - name: mytomcat
      image: tomee
      ports: 
       - containerPort: 8080
         hostPort: 9090
...
