---
apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
  labels:
    app: author
spec:
  containers:
    - name: affinity-cont
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slave1
                operator: In
                values: 
                  - intelliqit1
...

