---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: proxy
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /home/shaikakbarazure/practicek8s
...

