---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc
  labels:
    type: aauthor
spec:
  replicas: 3 
  template:
    metadata:
      name: httpd-pod
      labels:
        type: mypod
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8888
...
