---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myreplica
  labels:
    type: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: proxy
    spec:
      containers:
        - name: mytomcat
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 8080
...
