---
apiVersion: v1
kind: Service
metadata: 
   name: loadbalancerservice
   labels:
     app: proxy
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30010
  selector:
     author: intelliqit
...

