---
apiVersion: v1
kind: Pod
metadata: 
  name: nginxpod
  labels:
    app: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
  tolerations:
    - key: slave2
      operator: Equal
      value: intelliqit2
      effect: NoSchedule
...

