---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  labels:
    app: author
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: secret-pod
      labels: 
        app: proxy
    spec:
      containers: 
        - name: secret-postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: dbname
...  
