---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-dep
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: pod-post
      labels:
        app: proxy
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: intelliqit
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              value: username
...
