---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-dep
  labels:
    app: author2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: author2
  template:
    metadata:
      name: result-pod
      labels:
        app: author2
    spec:
      containers:
        - name: myresult
          image: docker/example-voting-app-result
...
