---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-dep
  labels:
    app: author
spec:
  replicas: 2
  selector:
    matchLabels:
      app: author
  template:
    metadata:
      name: voting-pod
      labels:
        app: author
    spec:
      containers:
        - name: myvote
          image: docker/example-voting-app-vote
...
