---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep2
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      name: pod-tomcat
      labels:
        app: proxy
    spec:
      containers:
        - name: tomcat
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 5555
...
