---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep3
  labels:
    app: author
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author
  template:
    metadata:
      name: pod-tomcat
      labels:
        app: author
    spec:
      containers:
        - name: apache
          image: httpd
          ports:
            - containerPort: 8080
              hostPort: 9999
...
