---
apiVersion: v1
kind: Service
metadata:
   name: nginx-service
   labels:
     app: proxy
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      
  selector:
    app: baigan
...

